# -*- coding: utf-8 -*-
"""gerandoUmchat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwdawwxZlLx7qwwnLr_i_ki6G6xHoF4n

Rodando a IA no google colab
"""

import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GEMINI_API_KEY')

from google import  genai

client = genai.Client()

chat = client.chats.create(model="gemini-2.5-flash")

resposta = client.models.generate_content(model="gemini-2.5-flash", contents="o que é a Inteligência Artificial?")
print(resposta.text)

resposta = chat.send_message("o que é a Inteligência Artificial?")
print(resposta.text)

prompt = input("Digite sua pergunta: ")

while prompt != "fim":
  resposta = chat.send_message(prompt)
  print(resposta.text)
  print("\n")
  prompt = input("Digite sua pergunta: ")